### ISSUE TITLE
读写data0等寄存器问题

### ISSUE THREAD

**Issue by LIGHTss** [Virus-V/SmartOCD#2]
实验平台：riscv（bl602）
问题：在向data0寄存器写入数据时，通过dmi操作dm寄存器，写入值0xabcd1234，而读出数据为0x6bcd1234。
现象如下图所示：
![image](https://user-images.githubusercontent.com/38397941/153434631-88c24cc8-5fc8-4f87-af5e-a04884e216a8.png)
通过逻辑分析仪，读出的数据command的data位值为0xabcd1234，具体现象如下：
![image](https://user-images.githubusercontent.com/38397941/153434794-66379c9b-fe2e-4618-9af2-df7bd10daf8e.png)

**Comment by Virus-V** [comment]
提供一下测试代码，以及log
